const SOURCE = {
  kind: 'manual',
  entity_unit_numbers: [],
  recipe_ids: [],
  evidence_refs: ['curated:factorio-basic-playbook-v1'],
}

function verification() {
  return {
    structural: 'not_tested',
    recipe_flow: 'not_tested',
    placement_rebuild: 'not_tested',
    production_output: 'not_tested',
    belt_capacity: 'unvalidated',
    inserter_sustained_throughput: 'unvalidated',
    acceptance_conditions: [],
  }
}

function confidence() {
  return {
    level: 'medium',
    basis: [
      'Curated early-game Factorio gameplay pattern.',
      'Pattern is guidance only; live recipe, prototype, inventory, placement, geometry, and world state must be revalidated before execution.',
    ],
  }
}

export const BASIC_SKILL_DEFINITIONS: any[] = [
  {
    schema_version: 1,
    revision: 1,
    id: 'buffered-building-stock',
    name: 'Buffered Building and Supply Stock',
    kind: 'production',
    stage: 'pattern',
    status: 'candidate',
    summary: 'Buffered stock: buildings generally ≥2 live stacks, belts ~400–600 each tier; player quantities win; never cap science or continuous flows. Choose a grounded target and control output inserters from the exact destination chest count.',
    goal_tags: ['buffer', 'stock', 'buildings', 'supplies', 'mall', 'belt'],
    source: SOURCE,
    preconditions: [
      { kind: 'custom', subject: 'buffered-output', description: 'The requested output is reusable stored stock, with a verified item identity and destination chest.' },
      { kind: 'custom', subject: 'live-stack-size', description: 'Read the current item prototype stack size before choosing a building stock quantity.' },
    ],
    inputs: [{ item: 'recipe-inputs', role: 'Automated supply for the grounded buffered recipe' }],
    outputs: [{ item: 'buffered-stock', role: 'Building or supply stock in the requested chest' }],
    topology: {
      nodes: [
        { id: 'producer', role: 'Machine making the buffered item' },
        { id: 'output-inserter', role: 'Bounded output transfer into storage' },
        { id: 'stock-chest', role: 'Exact destination and item-count signal source' },
      ],
      relations: [
        { kind: 'item_transfer', from: 'producer', to: 'output-inserter', description: 'Take only the buffered item from the verified producer output.' },
        { kind: 'item_transfer', from: 'output-inserter', to: 'stock-chest', description: 'Deliver into the exact storage chest.' },
        { kind: 'custom', from: 'stock-chest', to: 'output-inserter', description: 'Enable the output inserter while the item-count signal is below the chosen target.' },
      ],
    },
    constraints: [
      { kind: 'resource', description: 'Use at least two live item stacks as general building-stock guidance and approximately 400–600 items for each belt tier. The planner chooses the target from actual demand, recipe costs, capacity and player quantities.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'safety', description: 'Science and other continuously consumed production flows have no stock cap from this pattern. Do not apply a buffered-stock condition to their output inserters.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Before circuit mutation, verify exact entities, force, surface, reach and existing wiring; preserve unrelated networks and player constraints.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'capacity', description: 'Read back the chest signal and inserter condition. Verify production stops at the target with bounded carried-stack overshoot and restarts after withdrawal.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'stock_item', description: 'Verified reusable buffered item.', required: true },
      { name: 'target_count', description: 'Grounded target selected by the planner; an explicit player quantity takes precedence.', required: true },
      { name: 'output_chest', description: 'Exact authorized destination chest; never a science measurement chest.', required: true },
    ],
    verification: verification(),
    known_failure_modes: [
      'A guessed stack size creates the wrong building target.',
      'A science line is capped as if it were a building buffer.',
      'Other wired storage changes the signal counted by the output inserter.',
      'Carried inserter stacks cause overshoot that was not bounded or tested.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Maintain a belt buffer around a planner-chosen 400–600 target.', notes: 'The same guidance applies to every live belt tier. If the player requests an exact different quantity, use that quantity.' },
    ],
  },
  {
    schema_version: 1,
    revision: 2,
    id: 'missing-item-bootstrap',
    name: 'Missing Item Bootstrap',
    kind: 'utility',
    stage: 'pattern',
    status: 'candidate',
    summary: 'When a required building or item is absent, resolve the dependency before declaring a blocker: check held inventory, reusable nearby infrastructure, current recipe/craftability, required ingredients, then obtain or craft only what the next executable step needs. Missing does not mean unavailable.',
    goal_tags: ['missing', 'craft', 'bootstrap', 'dependency', 'blocked'],
    source: SOURCE,
    preconditions: [
      { kind: 'bootstrap', subject: 'required-item-missing', description: 'The current goal needs an item or building that SGLuna does not already have ready to use.' },
    ],
    inputs: [{ item: 'missing-required-item', role: 'dependency to resolve' }],
    outputs: [{ item: 'usable-required-item', role: 'dependency made available for the next action' }],
    topology: {
      nodes: [
        { id: 'goal', role: 'Current production or construction goal' },
        { id: 'required-item', role: 'Missing item or building required by the goal' },
        { id: 'recipe', role: 'Live enabled recipe or other grounded acquisition route' },
        { id: 'ingredients', role: 'Required inputs for the chosen acquisition route' },
      ],
      relations: [
        { kind: 'custom', from: 'goal', to: 'required-item', description: 'Identify only the dependency that blocks the next executable step.' },
        { kind: 'custom', from: 'recipe', to: 'required-item', description: 'Use live recipe knowledge to decide whether SGLuna can make the dependency.' },
        { kind: 'custom', from: 'ingredients', to: 'recipe', description: 'Acquire only ingredients actually required by the live recipe.' },
      ],
    },
    constraints: [
      { kind: 'safety', description: 'Do not guess recipe availability, ingredient counts, or hand-craftability from memory; query live recipe/prototype knowledge.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'resource', description: 'Do not search the world broadly for a missing building before checking whether SGLuna can craft it from held or obtainable ingredients.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'custom', description: 'Stop observing and commit the next action once the missing dependency is grounded well enough to act.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'required_item', description: 'Item or placeable building currently blocking the goal.', required: true },
    ],
    verification: verification(),
    known_failure_modes: [
      'Repeated nearby-entity scans even though the missing item can be crafted.',
      'Declaring blocked because the item is not in inventory without checking its enabled recipe.',
      'Crafting a remembered item identity or recipe that the current force/mod set does not actually provide.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Need a furnace to make iron plates but none is held or nearby.', notes: 'Check the furnace recipe and ingredients first; craft it if live knowledge proves that route, otherwise resolve the specific missing ingredient or report the real blocker.' },
    ],
  },
  {
    schema_version: 1,
    revision: 2,
    id: 'burner-coal-loop',
    name: 'Burner Coal Loop',
    kind: 'production',
    stage: 'pattern',
    status: 'candidate',
    summary: 'Bootstrap early coal production with a small amount of starter fuel, then arrange fuel-burning miners so mined coal feeds the fuel demand of the loop and surplus coal can be taken away. This is the common coal-snake / 煤蛇 idea; exact miner count, orientation, and geometry must come from the live world.',
    goal_tags: ['coal', 'coal-snake', 'burner', 'fuel', 'mining', '煤蛇'],
    source: SOURCE,
    preconditions: [
      { kind: 'entity_available', subject: 'burner-mining-drill', description: 'A placed or placeable fuel-burning mining machine (burner-mining-drill in the base game) can mine coal.' },
      { kind: 'custom', subject: 'coal-resource', description: 'A suitable fuel resource patch is available.' },
      { kind: 'bootstrap', subject: 'starter-fuel', description: 'Enough initial fuel exists to start at least part of the loop.' },
    ],
    inputs: [{ item: 'starter-fuel', role: 'initial bootstrap fuel' }, { item: 'coal-resource', role: 'mined resource' }],
    outputs: [{ item: 'coal', role: 'self-sustaining fuel plus surplus' }],
    topology: {
      nodes: [
        { id: 'miner-a', role: 'Coal miner and fuel consumer', entity_name: 'burner-mining-drill' },
        { id: 'miner-b', role: 'Next coal miner and fuel consumer', entity_name: 'burner-mining-drill' },
        { id: 'surplus', role: 'Optional coal takeoff after the loop is stable' },
      ],
      relations: [
        { kind: 'direct_item_output', from: 'miner-a', to: 'miner-b', description: 'Orient direct mining output so coal reaches the next miner fuel path when the runtime geometry supports it.' },
        { kind: 'direct_item_output', from: 'miner-b', to: 'miner-a', description: 'Close or extend the loop only after verifying actual output/fuel behavior.' },
        { kind: 'custom', from: 'miner-b', to: 'surplus', description: 'Take surplus only after the miners remain fueled.' },
      ],
    },
    constraints: [
      { kind: 'placement', description: 'Every miner must cover coal and its actual output direction must line up with the intended receiving fuel inventory or transfer path.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'resource', description: 'Reserve enough starter fuel to survive startup before the first mined coal reaches the next consumer.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'capacity', description: 'Do not assume the loop has useful surplus until live inventories/output show that production exceeds self-fueling demand.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'miner_count', description: 'Number of miners used in the loop; choose from actual patch geometry and available items.', required: false, default_value: 2 },
      { name: 'surplus_destination', description: 'Optional destination for coal after self-fueling is stable.', required: false },
    ],
    verification: verification(),
    known_failure_modes: [
      'One miner points at empty ground instead of the next fuel path.',
      'All mined coal is consumed internally and no surplus reaches the requested consumer.',
      'The loop is laid out from remembered sprite geometry rather than observed output direction and resource coverage.',
      'No starter fuel is inserted, so the loop never begins.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Early coal snake / 煤蛇.', notes: 'Use runtime placement, prototype, and entity geometry to build the local variant instead of assuming one fixed screenshot layout.' },
    ],
  },
  {
    schema_version: 1,
    revision: 3,
    id: 'direct-miner-smelting',
    name: 'Direct Miner Smelting',
    kind: 'production',
    stage: 'pattern',
    status: 'candidate',
    summary: 'For very early plate production, consider placing a mining drill so its output feeds a furnace directly, eliminating a belt and input inserter when live geometry permits. Fuel remains a separate dependency unless the selected machines do not require it.',
    goal_tags: ['smelting', 'smelt', 'iron', 'copper', 'ore', 'furnace', 'mining'],
    source: SOURCE,
    preconditions: [
      { kind: 'custom', subject: 'smeltable-resource', description: 'The target resource can be mined at the selected location.' },
      { kind: 'entity_available', subject: 'mining-drill', description: 'A compatible mining machine (entity type mining-drill) is available or can be made.' },
      { kind: 'entity_available', subject: 'furnace', description: 'A compatible smelting machine is available or can be made.' },
    ],
    inputs: [{ item: 'ore', role: 'mined input' }, { item: 'fuel', role: 'optional machine fuel when required' }],
    outputs: [{ item: 'plate', role: 'smelted output' }],
    topology: {
      nodes: [
        { id: 'miner', role: 'Mine the target resource', entity_name: 'burner-mining-drill' },
        { id: 'furnace', role: 'Receive miner output and smelt it', entity_name: 'stone-furnace' },
      ],
      relations: [
        { kind: 'direct_item_output', from: 'miner', to: 'furnace', description: 'Align the actual miner output with the furnace input footprint.' },
        { kind: 'adjacent', from: 'miner', to: 'furnace', description: 'Keep the machines close enough for the direct output relation proved by runtime geometry.' },
      ],
    },
    constraints: [
      { kind: 'placement', description: 'Validate mining resource coverage and the miner output position before construction.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'resource', description: 'Resolve furnace fuel independently; direct ore output does not automatically fuel the furnace.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'custom', description: 'Use live recipe knowledge to confirm the selected ore is accepted by the selected furnace class.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'resource', description: 'Resource to mine and smelt.', required: true },
      { name: 'furnace_output_plan', description: 'How SGLuna will collect or route finished plates.', required: false },
    ],
    verification: verification(),
    known_failure_modes: [
      'Miner output points beside the furnace instead of into it.',
      'The furnace receives ore but has no fuel.',
      'The selected furnace cannot process the live recipe/category.',
      'The drill was placed adjacent to ore but its mining area does not actually cover resource entities.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Bootstrap a few iron plates with existing early infrastructure.', notes: 'Prefer an already placed compatible miner/furnace pair when available; otherwise validate exact placement before building.' },
      { summary: 'To grow beyond the first pair, or to meet a rate or deadline, follow skill scale-out-production-line.', notes: 'It sizes the pair count from the rate tools and covers the early snowball.' },
    ],
  },
  {
    schema_version: 1,
    revision: 3,
    id: 'starter-smelting-row',
    name: 'Starter Smelting Row',
    kind: 'production',
    stage: 'pattern',
    status: 'candidate',
    summary: 'Scale early smelting by arranging multiple furnaces along repeatable ore/fuel input and plate output paths. Start with the smallest row that satisfies the immediate goal, preserve room to extend it, and validate belt/inserter capacity rather than assuming a remembered ratio.',
    goal_tags: ['smelting', 'smelting-row', 'smelt', 'furnace-row', 'row', 'iron', 'copper', 'furnace'],
    source: SOURCE,
    preconditions: [
      { kind: 'entity_available', subject: 'furnace', description: 'One or more compatible furnaces are available or craftable.' },
      { kind: 'entity_available', subject: 'item-transport', description: 'A workable input/output transport method exists, such as belts and inserters or direct manual supply.' },
    ],
    inputs: [{ item: 'ore', role: 'smelting input' }, { item: 'fuel', role: 'fuel when required' }],
    outputs: [{ item: 'plate', role: 'smelting output' }],
    topology: {
      nodes: [
        { id: 'input-path', role: 'Deliver ore and optional fuel' },
        { id: 'furnace-row', role: 'Repeatable furnace cells', entity_name: 'stone-furnace' },
        { id: 'output-path', role: 'Collect finished plates' },
      ],
      relations: [
        { kind: 'belt_input', from: 'input-path', to: 'furnace-row', description: 'Each furnace cell receives the required live recipe inputs.' },
        { kind: 'belt_output', from: 'furnace-row', to: 'output-path', description: 'Finished plates leave without blocking furnace output.' },
      ],
    },
    constraints: [
      { kind: 'capacity', description: 'Use live belt and inserter capacity when rate matters; do not assume a classic furnace ratio is valid for the current prototypes/research.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Reserve a clear extension direction so the row can grow without rebuilding the first cells.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'resource', description: 'If fuel shares an input belt with ore, verify both lanes remain supplied and correctly separated.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'furnace_count', description: 'Initial number of furnace cells.', required: false, default_value: 4 },
      { name: 'extension_direction', description: 'Direction reserved for adding more furnace cells.', required: false },
    ],
    verification: verification(),
    known_failure_modes: [
      'Furnaces starve because ore and fuel were merged onto the same lane accidentally.',
      'Output blocks because the plate belt/inventory has no room.',
      'The row is boxed in and cannot be extended.',
      'A remembered vanilla throughput ratio is treated as deterministic truth.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Build a small iron or copper smelting row that can be extended later.', notes: 'For tiny goals, direct manual supply may be cheaper than building the full transport pattern.' },
      { summary: 'To size the row for a rate or deadline, or to extend it, follow skill scale-out-production-line.', notes: 'It sizes the furnace count from the rate tools instead of a remembered ratio.' },
    ],
  },
  {
    schema_version: 1,
    revision: 2,
    id: 'two-item-half-belt',
    name: 'Two Item Half-Belt',
    kind: 'logistics',
    stage: 'pattern',
    status: 'candidate',
    summary: 'Carry two low-throughput item streams on opposite lanes of one belt so a shared consumer row can access both without two full belts. Common early uses include ore plus fuel or two assembler ingredients; validate actual lane occupancy and consumer pickup geometry.',
    goal_tags: ['half-belt', 'lane', 'belt', 'logistics', '半带'],
    source: SOURCE,
    preconditions: [
      { kind: 'entity_available', subject: 'transport-belt', description: 'A belt or equivalent two-lane transport is available.' },
      { kind: 'bootstrap', subject: 'two-low-throughput-streams', description: 'Two distinct streams fit within the available per-lane capacity.' },
    ],
    inputs: [{ item: 'stream-a', role: 'one belt lane' }, { item: 'stream-b', role: 'opposite belt lane' }],
    outputs: [{ item: 'shared-two-lane-belt', role: 'compact combined transport' }],
    topology: {
      nodes: [
        { id: 'stream-a', role: 'First item source' },
        { id: 'stream-b', role: 'Second item source' },
        { id: 'shared-belt', role: 'Two-lane shared belt', entity_name: 'transport-belt' },
        { id: 'consumers', role: 'Machines or inserters reading both required streams' },
      ],
      relations: [
        { kind: 'belt_input', from: 'stream-a', to: 'shared-belt', description: 'Load stream A onto one lane only.' },
        { kind: 'belt_input', from: 'stream-b', to: 'shared-belt', description: 'Load stream B onto the other lane only.' },
        { kind: 'belt_output', from: 'shared-belt', to: 'consumers', description: 'Consumers must physically reach the required lane/items.' },
      ],
    },
    constraints: [
      { kind: 'capacity', description: 'Each stream must fit its lane capacity with headroom for bursts and inserter behavior.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Verify side-loading/inserter drop behavior so the streams remain on opposite lanes instead of mixing onto one lane.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'stream_a_item', description: 'Item assigned to one lane.', required: true },
      { name: 'stream_b_item', description: 'Item assigned to the opposite lane.', required: true },
    ],
    verification: verification(),
    known_failure_modes: [
      'Both streams land on the same lane and one material starves consumers.',
      'One lane saturates and backs up the upstream source.',
      'A consumer inserter cannot reach or distinguish the intended stream in the actual topology.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Early half-belt merge / 半带并线.', notes: 'Useful when two ingredients each need much less than a full belt.' },
    ],
  },
  {
    schema_version: 1,
    revision: 2,
    id: 'belt-side-load-merge',
    name: 'Belt Side-Load Merge',
    kind: 'logistics',
    stage: 'pattern',
    status: 'candidate',
    summary: 'Merge or compress belt streams by side-loading one belt into another when the resulting lane semantics and throughput are useful. Use this for compact early merges or to combine two partial same-item streams, but verify belt direction and lane occupancy instead of copying a remembered layout.',
    goal_tags: ['side-load', 'merge', 'belt', 'logistics', '并线'],
    source: SOURCE,
    preconditions: [
      { kind: 'entity_available', subject: 'transport-belt', description: 'At least two belt segments or streams need to be joined.' },
    ],
    inputs: [{ item: 'belt-stream-a', role: 'continuing belt' }, { item: 'belt-stream-b', role: 'side-loaded belt' }],
    outputs: [{ item: 'merged-belt-stream', role: 'combined transport path' }],
    topology: {
      nodes: [
        { id: 'main-belt', role: 'Receiving belt that continues toward consumers', entity_name: 'transport-belt' },
        { id: 'side-belt', role: 'Belt entering from the side' },
        { id: 'merge', role: 'Side-load junction' },
      ],
      relations: [
        { kind: 'belt_output', from: 'side-belt', to: 'merge', description: 'Side stream enters the receiving belt from a verified direction.' },
        { kind: 'belt_input', from: 'main-belt', to: 'merge', description: 'Main stream preserves its intended travel direction.' },
        { kind: 'belt_output', from: 'merge', to: 'main-belt', description: 'Merged items continue toward the target consumers.' },
      ],
    },
    constraints: [
      { kind: 'capacity', description: 'The combined stream must fit the destination lane/belt capacity; merging cannot create throughput above the live belt limit.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Inspect belt direction and current lane occupancy before changing an existing line.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'merge_goal', description: 'Whether the goal is compact routing, lane assignment, or combining partial same-item throughput.', required: true },
    ],
    verification: verification(),
    known_failure_modes: [
      'Side-loading reverses or blocks an existing route.',
      'The merge fills the wrong lane for downstream consumers.',
      'Two already-full streams are merged and throughput is silently lost.',
    ],
    confidence: confidence(),
    examples: [
      { summary: '并线加速 / compact belt merge.', notes: 'Treat side-loading as a topology pattern, not as a magic throughput multiplier.' },
    ],
  },
  {
    schema_version: 1,
    revision: 2,
    id: 'direct-insertion-chain',
    name: 'Direct Insertion Chain',
    kind: 'logistics',
    stage: 'pattern',
    status: 'candidate',
    summary: 'When one producer mainly feeds one nearby consumer, prefer a short direct-insertion relationship over unnecessary belts if live recipe flow, geometry, and inserter reach support it. This reduces early material handling and can make compact intermediate chains.',
    goal_tags: ['direct-insertion', 'inserter', 'intermediate', 'chain'],
    source: SOURCE,
    preconditions: [
      { kind: 'entity_available', subject: 'producer-machine', description: 'A producer machine or furnace creates the intermediate item.' },
      { kind: 'entity_available', subject: 'consumer-machine', description: 'A downstream machine consumes that intermediate.' },
      { kind: 'entity_available', subject: 'item-transfer', description: 'A direct output or inserter transfer can connect them.' },
    ],
    inputs: [{ item: 'upstream-input', role: 'producer input' }],
    outputs: [{ item: 'downstream-output', role: 'consumer output' }],
    topology: {
      nodes: [
        { id: 'producer', role: 'Produce the intermediate item' },
        { id: 'transfer', role: 'Short direct item transfer', entity_name: 'inserter' },
        { id: 'consumer', role: 'Consume the intermediate item' },
      ],
      relations: [
        { kind: 'item_transfer', from: 'producer', to: 'consumer', via: 'transfer', description: 'Use actual pickup/drop targets or direct output geometry to prove the connection.' },
      ],
    },
    constraints: [
      { kind: 'capacity', description: 'Do not infer inserter items-per-second from stack size or rotation speed; measure/verify when sustained throughput matters.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Use actual runtime pickup/drop geometry for placed inserters and machines.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'resource', description: 'The consumer may still need another independent ingredient stream; direct insertion only solves the linked intermediate.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'intermediate_item', description: 'Intermediate item passed directly from producer to consumer.', required: true },
    ],
    verification: verification(),
    known_failure_modes: [
      'Inserter pickup/drop points do not actually touch the intended machines.',
      'The direct transfer cannot keep up with the consumer.',
      'The consumer is starved of another ingredient that the direct link does not provide.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Feed an early intermediate producer directly into the machine that consumes most of that intermediate.', notes: 'Useful for compact gear/component chains when the live recipes make the relationship sensible.' },
    ],
  },
  {
    schema_version: 1,
    revision: 2,
    id: 'steam-power-bootstrap',
    name: 'Steam Power Bootstrap',
    kind: 'construction',
    stage: 'pattern',
    status: 'candidate',
    summary: 'Bring up the first reliable electric power with the smallest live-compatible water-to-steam-to-generator chain, then connect the electrical network and fuel the heat source. Verify fluidbox geometry, connection direction, fuel state, and generated power instead of relying on a memorized blueprint.',
    goal_tags: ['power', 'electricity', 'electric', 'steam', 'steam-power', 'electric-network'],
    source: SOURCE,
    preconditions: [
      { kind: 'entity_available', subject: 'offshore-pump', description: 'A live-compatible water source entity (offshore-pump in the base game) can be placed on reachable water.' },
      { kind: 'entity_available', subject: 'boiler', description: 'A compatible heating entity (entity type boiler) is available or craftable.' },
      { kind: 'entity_available', subject: 'generator', description: 'A compatible generation entity (entity type generator, e.g. steam-engine) is available or craftable.' },
      { kind: 'bootstrap', subject: 'fuel-or-energy-input', description: 'The heat source can receive its required initial energy input.' },
    ],
    inputs: [{ item: 'water', role: 'fluid input' }, { item: 'fuel', role: 'heat source input when required' }],
    outputs: [{ item: 'electric-power', role: 'starter electrical supply' }],
    topology: {
      nodes: [
        { id: 'water-source', role: 'Provide water to the steam chain', entity_name: 'offshore-pump' },
        { id: 'heater', role: 'Convert water/energy into generator-compatible working fluid', entity_name: 'boiler' },
        { id: 'generator', role: 'Generate electric power', entity_name: 'steam-engine' },
        { id: 'grid', role: 'Electrical network used by early machines', entity_name: 'small-electric-pole' },
      ],
      relations: [
        { kind: 'fluid_connection', from: 'water-source', to: 'heater', description: 'Connect live output/input fluidboxes.' },
        { kind: 'fluid_connection', from: 'heater', to: 'generator', description: 'Connect compatible steam/working-fluid ports.' },
        { kind: 'custom', from: 'generator', to: 'grid', description: 'Place power distribution so intended consumers are actually connected.' },
      ],
    },
    constraints: [
      { kind: 'placement', description: 'Water-source placement is terrain-dependent; validate the actual shoreline/site.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Use prototype/runtime fluidbox roles and positions rather than remembered pipe-port directions.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'resource', description: 'A burner heater is not operational until fuel is actually available in its fuel path.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'power_goal', description: 'Immediate machines or load that must be powered.', required: false },
      { name: 'extension_direction', description: 'Direction reserved for adding generation later.', required: false },
    ],
    verification: verification(),
    known_failure_modes: [
      'Fluid ports are adjacent visually but not actually connected.',
      'The boiler/heater has water but no fuel.',
      'The generator is running but the target machines are outside the electrical network.',
      'A large power plant is built before a minimal starter chain was needed.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'First steam power / early electricity bootstrap.', notes: 'Resolve actual current-game prototypes and fluid connections before placement; do not assume vanilla dimensions or ratios.' },
    ],
  },
  {
    schema_version: 1,
    revision: 2,
    id: 'starter-mining-belt-output',
    name: 'Starter Mining Belt Output',
    kind: 'production',
    stage: 'pattern',
    status: 'candidate',
    summary: 'Build an early scalable mining row by placing drills that genuinely cover the resource patch and orienting their outputs onto a shared belt or other collection path. Keep power/fuel coverage and belt capacity explicit, and extend along the patch only after the first cells are verified.',
    goal_tags: ['mining', 'mining-row', 'ore', 'drill', 'belt'],
    source: SOURCE,
    preconditions: [
      { kind: 'custom', subject: 'resource-patch', description: 'The target resource patch has observed entities in the intended build area.' },
      { kind: 'entity_available', subject: 'mining-drill', description: 'A compatible mining machine (entity type mining-drill) is available or craftable.' },
      { kind: 'entity_available', subject: 'collection-path', description: 'A belt or other bounded output collection path is available.' },
    ],
    inputs: [{ item: 'resource-patch', role: 'mining source' }, { item: 'power-or-fuel', role: 'mining energy input' }],
    outputs: [{ item: 'mined-resource', role: 'belted or collected output' }],
    topology: {
      nodes: [
        { id: 'drill-row', role: 'Mining machines covering the resource patch', entity_name: 'electric-mining-drill' },
        { id: 'output-belt', role: 'Shared collection belt or equivalent path', entity_name: 'transport-belt' },
        { id: 'power', role: 'Power/fuel coverage for the mining row' },
      ],
      relations: [
        { kind: 'direct_item_output', from: 'drill-row', to: 'output-belt', description: 'Each drill output must actually land on the collection path.' },
        { kind: 'custom', from: 'power', to: 'drill-row', description: 'Each drill receives the energy source required by its live prototype.' },
      ],
    },
    constraints: [
      { kind: 'resource', description: 'Use live mining radius/resource coverage; body overlap with a patch is not sufficient evidence that a drill can mine it.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'capacity', description: 'A shared output belt must have enough lane/belt capacity for the drills that feed it.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Reserve a sensible extension direction along the observed patch.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'resource_name', description: 'Resource prototype being mined.', required: true },
      { name: 'initial_drill_count', description: 'Number of drills to build before verifying output.', required: false, default_value: 2 },
    ],
    verification: verification(),
    known_failure_modes: [
      'Drills are on the patch but their working area misses the actual resource entities.',
      'One drill outputs to ground because its direction differs from the rest.',
      'The collection belt saturates or uses the wrong lane downstream.',
      'Electric drills are placed without actual power coverage.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Early electric mining row feeding one belt.', notes: 'Prefer a small verified row before filling the entire ore patch.' },
    ],
  },
  {
    schema_version: 1,
    revision: 2,
    id: 'automation-science-bootstrap',
    name: 'Automation Science Bootstrap',
    kind: 'production',
    stage: 'pattern',
    status: 'candidate',
    summary: 'Bootstrap the first science-pack production by resolving the live science recipe into a small dependency chain, producing any simple intermediate locally, feeding the remaining ingredients, and routing finished packs toward labs or storage. Use live recipe knowledge because modded science recipes may differ from vanilla.',
    goal_tags: ['science', 'red-science', 'automation-science', 'research', 'lab', '红瓶'],
    source: SOURCE,
    preconditions: [
      { kind: 'technology_researched', subject: 'automation', description: 'The force has researched the technology that unlocks crafting machines for the live science-pack and intermediate recipes (automation in the base game).' },
      { kind: 'bootstrap', subject: 'science-goal', description: 'The task requires early automated research supply rather than one-off manual crafting.' },
    ],
    inputs: [{ item: 'science-ingredients', role: 'live recipe inputs' }],
    outputs: [{ item: 'automation-science-pack', role: 'first automated science output or current-game equivalent' }],
    topology: {
      nodes: [
        { id: 'intermediate-producer', role: 'Produce a repeated intermediate when the live recipe requires one' },
        { id: 'science-assembler', role: 'Craft the target science pack', entity_name: 'assembling-machine-1', recipe: 'automation-science-pack' },
        { id: 'ingredient-feed', role: 'Supply other recipe ingredients' },
        { id: 'science-output', role: 'Collect or deliver finished science packs' },
      ],
      relations: [
        { kind: 'item_transfer', from: 'intermediate-producer', to: 'science-assembler', description: 'Prefer a short direct insertion when one intermediate mostly serves this assembler and geometry allows it.' },
        { kind: 'belt_input', from: 'ingredient-feed', to: 'science-assembler', description: 'Feed the remaining live-recipe ingredients.' },
        { kind: 'belt_output', from: 'science-assembler', to: 'science-output', description: 'Make finished packs available to the intended research path.' },
      ],
    },
    constraints: [
      { kind: 'custom', description: 'Always query the live science recipe and intermediate recipes; do not assume vanilla ingredient identities or counts.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'capacity', description: 'A starter line only needs to meet the current research goal; avoid overbuilding until actual demand/throughput is known.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Verify machine recipes, inserter targets, and output access after construction.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'science_item', description: 'Target early science-pack item in the current game.', required: false, default_value: 'automation-science-pack' },
      { name: 'target_rate', description: 'Optional desired production rate; if supplied, solve from live recipes instead of remembered ratios.', required: false },
    ],
    verification: verification(),
    known_failure_modes: [
      'The model assumes the vanilla red-science recipe in a modded game.',
      'The intermediate producer works but the science assembler is missing its other ingredient.',
      'Finished science packs accumulate in a machine because no output path exists.',
      'A memorized assembler ratio is treated as validated throughput.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Red science / 红瓶 bootstrap.', notes: 'In vanilla this often benefits from a compact intermediate-to-science relationship, but the current recipe graph is authoritative.' },
    ],
  },
  {
    schema_version: 1,
    revision: 1,
    id: 'scale-out-production-line',
    name: 'Scale Out A Production Line',
    kind: 'production',
    stage: 'pattern',
    status: 'candidate',
    goal_tags: ['scale-out', 'scale', 'throughput', 'rate', 'per-minute', 'per-second', 'more-machines', 'expand', 'snowball', 'parallel', 'faster', 'deadline'],
    summary: 'Grow a working production cell by copying it, with the machine count sized from measured game rates instead of remembered ratios. Ask the rate tools how long the job takes with N machines, choose the count that meets the rate or deadline and still pays back its own build time, then copy the proven cell using the footprints the placement tools return. Early on, snowball: the first pair\'s plates pay for the next drills and furnaces.',
    source: SOURCE,
    preconditions: [
      { kind: 'bootstrap', subject: 'working-production-cell', description: 'At least one cell of the line (for example one miner feeding one furnace, or one assembler) is built and has been seen producing.' },
      { kind: 'custom', subject: 'target-rate-or-deadline', description: 'The goal names a rate (items per minute), an amount with a deadline, or the planner judged the current single lane too slow.' },
    ],
    inputs: [{ item: 'working-production-cell', role: 'proven cell to copy' }, { item: 'machine-materials', role: 'plates and parts for the added machines' }],
    outputs: [{ item: 'production-rate', role: 'more output per minute from identical cells' }],
    topology: {
      nodes: [
        { id: 'proven-cell', role: 'The first cell, verified producing' },
        { id: 'rate-check', role: 'Per-machine rate and whole-job time from the rate tools' },
        { id: 'added-cells', role: 'Copies of the proven cell, placed from returned footprints' },
        { id: 'shared-input', role: 'Ore, fuel or ingredient supply shared by the cells' },
        { id: 'shared-output', role: 'Where finished items from all cells are collected' },
      ],
      relations: [
        { kind: 'custom', from: 'rate-check', to: 'added-cells', description: 'Machine count = target rate / per-machine rate (getRecipeDetails for machines, getMiningDetails for drills); confirm the whole job with estimateProductionTime before building.' },
        { kind: 'custom', from: 'proven-cell', to: 'added-cells', description: 'Copy the proven relative layout. Place each machine from getPlacementCandidates, using covers_position for output/drop points and the returned footprint to keep cells apart.' },
        { kind: 'belt_input', from: 'shared-input', to: 'added-cells', description: 'Every added cell receives its inputs and fuel, not only the first one.' },
        { kind: 'belt_output', from: 'added-cells', to: 'shared-output', description: 'Output from every cell reaches the collection point without blocking.' },
      ],
    },
    constraints: [
      { kind: 'capacity', description: 'Size machine counts from live rates (getRecipeDetails crafts per second and output per minute; getMiningDetails ore and fuel per minute per drill) and check the result with estimateProductionTime. Never use a remembered ratio.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'capacity', description: 'Payback: each added machine costs crafting, materials, walking and placement time. Add it only when estimateProductionTime shows the time saved within the remaining job exceeds that cost; for a small job, fewer machines finish sooner.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'capacity', description: 'A shared belt or inserter has its own limit; use getTransportCapacity before feeding many cells from one input. Do not assume lane or inserter throughput.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'placement', description: 'Space cells by the footprint each placement candidate returns (tile size and world box); even-sized machines centre on whole tiles. Reserve the extension direction when building the first cell.', validation: 'unvalidated', evidence_refs: [] },
      { kind: 'resource', description: 'Every added burner machine needs its own fuel supply; fuel burn per minute comes from getMiningDetails.', validation: 'unvalidated', evidence_refs: [] },
    ],
    parameters: [
      { name: 'target_rate', description: 'Items per minute the goal asks for, if it names one.', required: false },
      { name: 'deadline_minutes', description: 'Time the job should finish within, if it names one.', required: false },
      { name: 'cell_skill', description: 'Skill id of the cell being copied, for example direct-miner-smelting or starter-smelting-row.', required: false },
    ],
    verification: verification(),
    known_failure_modes: [
      'Scaling before the first cell was seen producing, so every copy repeats its defect.',
      'Machine count taken from a remembered ratio instead of the rate tools.',
      'Adding machines to a small job where building them costs more time than they save.',
      'New cells overlap or block the extension direction because footprints were not used.',
      'Output capacity grows but the shared input, fuel or collection path cannot keep up.',
    ],
    confidence: confidence(),
    examples: [
      { summary: 'Snowball early plates: one burner drill feeding one furnace makes the plates for the next drill and furnace pair; repeat while estimateProductionTime shows the added pair still pays back.', notes: 'Counts come from the rate tools, never from this example.' },
      { summary: 'Rate goal such as N plates per minute: per-furnace rate from getRecipeDetails, per-drill ore rate from getMiningDetails, pick counts, check with estimateProductionTime, then build.', notes: 'Deadline goals work the same way with a target time instead of a rate.' },
    ],
  },
]
